### pandas

pandas is a powerfull phython library for manipulation are alanaysis pf publish_display_data
    
    its a open source library

fast(build on top of numpy) , flexible(different resource), productive library

install

In [188]:
import pandas as pd

In [189]:
pd.__version__

'2.2.3'

In [190]:
s= pd.Series(1, index = ["a","b","c","d","e"], name = "My series")

In [191]:
s

a    1
b    1
c    1
d    1
e    1
Name: My series, dtype: int64

In [192]:
s['a']

np.int64(1)

In [193]:
type(s)

pandas.core.series.Series

In [194]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

note : index in series are imuutable(cant change)

In [195]:
s.values

array([1, 1, 1, 1, 1])

In [196]:
#changing the index of a pandas series

s.rename(index={'b':'y'})

a    1
y    1
c    1
d    1
e    1
Name: My series, dtype: int64

In [197]:
s

a    1
b    1
c    1
d    1
e    1
Name: My series, dtype: int64


### DataFrame - Its a 2d array (just like tables)

In [198]:
dict1 = {'Name':['Virat','Rohit','Dhoni','Jadeja','Bumrah'],
         'Age':[34,33,40,32,30],
         'Role':['Batsman','Batsman','Wicket keeper','All Rounder','Bowler']
}
df = pd.DataFrame(dict1)

In [199]:
df

     Name  Age           Role
0   Virat   34        Batsman
1   Rohit   33        Batsman
2   Dhoni   40  Wicket keeper
3  Jadeja   32    All Rounder
4  Bumrah   30         Bowler

In [200]:
type(df)

pandas.core.frame.DataFrame

In [201]:
df.count()

Name    5
Age     5
Role    5
dtype: int64

In [202]:
df.head(4)

     Name  Age           Role
0   Virat   34        Batsman
1   Rohit   33        Batsman
2   Dhoni   40  Wicket keeper
3  Jadeja   32    All Rounder

In [203]:
df.tail(4)

     Name  Age           Role
1   Rohit   33        Batsman
2   Dhoni   40  Wicket keeper
3  Jadeja   32    All Rounder
4  Bumrah   30         Bowler

In [204]:
len(df)

5

In [205]:
df.columns

Index(['Name', 'Age', 'Role'], dtype='object')

In [206]:
df['Name'].value_counts

<bound method IndexOpsMixin.value_counts of 0     Virat
1     Rohit
2     Dhoni
3    Jadeja
4    Bumrah
Name: Name, dtype: object>

### Basic Operations 

> Importing data set from diffrent files 


> Importing tabular dataset

In [207]:
stock_df = pd.read_csv(r"C:\Users\klemp\Desktop\data analyst (vinayak)\datasets\ETH_1h.csv")

In [208]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

# Top 5 rows

In [209]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

# Top 10 rows

In [210]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

# Bottom 5 rows

In [211]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [212]:
## Number of rows in dataframe

len(stock_df)

23674

# Access column name of DataFrame

In [213]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [214]:
## Accessing a column in DataFrame

stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [215]:
## Accessing multiple columns in DataFrame

stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

# Assecing Rows

In [216]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [217]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [218]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

# Assccing Rows

loc - lable location

In [219]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [220]:
stock_df.loc[23673,['Date','Close','Open']]

Date     2017-07-01 11-AM
Close              275.01
Open               279.98
Name: 23673, dtype: object

In [221]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [222]:
stock_df.loc[23673,'Open':'Close']  # a:b

Open     279.98
High     279.99
Low       272.1
Close    275.01
Name: 23673, dtype: object

# iloc- index based location ,when we don't know labels for rows  and columns

In [223]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [224]:
stock_df.iloc[1]

Date      2020-03-13 07-PM
Symbol              ETHUSD
Open                119.51
High                132.02
Low                  117.1
Close               129.94
Volume          7579741.09
Name: 1, dtype: object

In [225]:
stock_df.iloc[1,2]

np.float64(119.51)

In [226]:
stock_df.iloc[3,[2,4]]

Open    124.08
Low     121.63
Name: 3, dtype: object

In [227]:
stock_df.iloc[2,2:6]

Open     124.47
High     124.85
Low       115.5
Close    119.51
Name: 2, dtype: object

In [228]:
stock_df.iloc[2:6,2:6]

     Open    High     Low   Close
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

# Filtering

In [229]:
f1 = stock_df

In [230]:
f1 = stock_df['High'] > 130 
 
stock_gt_130 = stock_df[f1]

In [231]:
stock_gt_130 = stock_df

In [232]:
stock_gt_130.reset_index(drop=True,inplace=True)

# Adding new column

In [260]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

In [261]:
len(stock_df)

23674

In [263]:
for i in range(0,3):
    print(i)

0
1
2

In [264]:
range(1,len(stock_df)+1)

range(1, 23675)

In [265]:
stock_df['Random_col']=list(range(1,len(stock_df)+1))

In [266]:
stock_df

                   Date  Symbol     Low   Close      Volume  Random_col
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93           1
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09           2
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81           3
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92           4
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71           5
...                 ...     ...     ...     ...         ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55       23670
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85       23671
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99       23672
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87       23673
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87       23674

[23674 rows x 6 columns]

# Dropping column

In [ ]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [256]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

In [273]:
stock_df.drop(columns=['Volume'],inplace=True)

In [274]:
stock_df

                   Date  Symbol     Low   Close
0      2020-03-13 08-PM  ETHUSD  126.87  128.71
1      2020-03-13 07-PM  ETHUSD  117.10  129.94
2      2020-03-13 06-PM  ETHUSD  115.50  119.51
3      2020-03-13 05-PM  ETHUSD  121.63  124.47
4      2020-03-13 04-PM  ETHUSD  120.17  124.08
...                 ...     ...     ...     ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01

[23674 rows x 4 columns]